### ISSUE TITLE
Code Documentation

### ISSUE THREAD

**Issue by AquaMorph** [team2059/Benjy#1]
Create GitHub Page and README for the 2014 code

**Comment by stonewareslord** [comment]
2014 or 2012?

**Comment by AquaMorph** [comment]
What does the issue say?

**Comment by stonewareslord** [comment]
2014

**Comment by AquaMorph** [comment]
There you go

**Comment by stonewareslord** [comment]
Benny is The Hitchhikers 2012 robot

**Comment by stonewareslord** [comment]
Benny is The Hitchhikers 2012 robot

**Comment by AquaMorph** [comment]
Yes but there are two version of the code. One from 2012 and then a rewrite I did in 2014

**Comment by stonewareslord** [comment]
Just making sure you didn't mistype anything

**Comment by AquaMorph** [comment]
Why would I specify code year if there wasn't two years of code? Clearly it was intentional

**Comment by stonewareslord** [comment]
Just making sure it wasn't mistyped.
